from collections import Counter

board = [
    {"color": "r"},
    {"color": "p"},
    {"color": "y"},
    {"color": "b"},
    {"color": "o", "bridge": "rainbow"},
    {"color": "g"},
    {"color": "r"},
    {"color": "p"},
    {"char": "ginger"},
    {"color": "y"},
    {"color": "b"},
    {"color": "o"},
    {"color": "g"},
    {"color": "r"},
    {"color": "p"},
    {"color": "y"},
    {"color": "b"},
    {"color": "o"},
    {"color": "g"},
    {"char": "candy"},
    {"color": "r"},
    {"color": "p"},
    {"color": "y"},
    {"color": "b"},
    {"color": "o"},
    {"color": "g"},
    {"color": "r"},
    {"color": "p"},
    {"color": "y"},
    {"color": "b"},
    {"color": "o"},
    {"color": "g"},
    {"color": "r"},
    {"color": "p"},
    {"color": "y", "bridge": "gumdrop"},
    {"color": "b"},
    {"color": "o"},
    {"color": "g"},
    {"color": "r"},
    {"color": "p"},
    {"color": "y"},
    {"char": "gumdrop"},
    {"color": "b"},
    {"color": "o"},
    {"color": "g", "end": "gumdrop"},
    {"color": "r", "special": "miss"},
    {"special": "skip"},
    {"color": "r"},
    {"color": "p"},
    {"color": "y"},
    {"color": "b"},
    {"color": "o"},
    {"color": "g"},
    {"color": "r"},
    {"color": "p"},
    {"color": "y"},
    {"color": "b"},
    {"color": "o"},
    {"color": "g"},
    {"color": "r"},
    {"color": "p", "end": "rainbow"},
    {"color": "y"},
    {"color": "b"},
    {"color": "o"},
    {"color": "g"},
    {"color": "r"},
    {"color": "p"},
    {"color": "y"},
    {"color": "b"},
    {"color": "o"},
    {"char": "grandma"},
    {"color": "g"},
    {"color": "r"},
    {"color": "p"},
    {"color": "y"},
    {"color": "b"},
    {"color": "o"},
    {"color": "g"},
    {"color": "r"},
    {"color": "p"},
    {"color": "y"},
    {"color": "b"},
    {"color": "o"},
    {"color": "g"},
    {"color": "r"},
    {"color": "p"},
    {"color": "y"},
    {"color": "b", "special": "miss"},
    {"special": "skip"},
    {"color": "o"},
    {"color": "g"},
    {"color": "r"},
    {"color": "p"},
    {"color": "y"},
    {"char": "lolly"},
    {"color": "b"},
    {"color": "o"},
    {"color": "g"},
    {"color": "r"},
    {"color": "p"},
    {"color": "y"},
    {"color": "b"},
    {"color": "o"},
    {"color": "g"},
    {"char": "queen"},
    {"color": "r"},
    {"color": "p"},
    {"color": "y"},
    {"color": "b"},
    {"color": "o"},
    {"color": "g"},
    {"color": "r"},
    {"color": "p"},
    {"color": "y"},
    {"color": "b"},
    {"color": "o"},
    {"color": "g"},
    {"color": "r"},
    {"color": "p"},
    {"color": "y", "special": "miss"},
    {"special": "skip"},
    {"color": "b"},
    {"color": "o"},
    {"color": "g"},
    {"color": "r"},
    {"color": "p"},
    {"color": "y"},
    {"color": "b"},
    {"color": "o"},
    {"color": "g"},
    {"color": "r"},
    {"color": "p"},
    {"color": "y"},
    {"color": "b"},
    {"color": "o"},
    {"color": "g"},
    {"color": "r"},
    {"color": "end"}
]

characters = ["ginger", "candy", "gumdrop", "grandma", "lolly", "queen"]

colors = ["r", "o", "y", "g", "b", "p"]

deck = Counter(
    {
        "r": 6,
        "rr": 4,
        "o": 6,
        "oo": 3,
        "y": 6,
        "yy": 4,
        "g": 6,
        "gg": 3,
        "b": 6,
        "bb": 4,
        "p": 6,
        "pp": 4,
        "ginger": 1,
        "candy": 1,
        "gumdrop": 1,
        "grandma": 1,
        "lolly": 1,
        "queen": 1
     }
)